const D=window.HELIA_DATA||{};const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const THEME='helia-theme';const APPT='helia-demo-appointments';
function theme(v){document.documentElement.dataset.theme=v;localStorage.setItem(THEME,v);$$('[data-theme]').forEach(b=>b.textContent=v==='dark'?'☀':'☾')}
function shell(){const h=$('[data-shell-header]');if(h)h.innerHTML='<header class="app-header"><div class="wrap app-header-row"><a class="brand" href="index.html"><span class="brand-mark"></span><span>HELIA</span></a><nav class="main-nav"><a href="especialidades.html">Especialidades</a><a href="equipe.html">Equipe</a><a href="agendamento.html">Agendamento</a><a href="portal.html">Portal</a></nav><div class="header-actions"><button class="icon-btn" data-theme aria-label="Alternar tema">☾</button><a class="secondary" href="portal.html">Área do paciente</a><a class="primary" href="agendamento.html">Agendar</a></div></div></header>';const f=$('[data-shell-footer]');if(f)f.innerHTML='<nav class="mobile-nav"><a href="index.html">⌂<span>Início</span></a><a href="agendamento.html">＋<span>Agendar</span></a><a href="portal.html">▣<span>Portal</span></a><a href="mensagens.html">✉<span>Mensagens</span></a></nav><footer class="app-footer"><div class="wrap footer-grid"><div><div class="brand"><span class="brand-mark"></span><span>HELIA</span></div><p>Plataforma conceitual de cuidado integrado desenvolvida pela Alureal.</p></div><div><strong>Atendimento</strong><p><a href="agendamento.html">Agendar</a><br><a href="teleconsulta.html">Teleconsulta</a><br><a href="planos.html">Convênios</a></p></div><div><strong>Paciente</strong><p><a href="portal.html">Portal</a><br><a href="exames.html">Exames</a><br><a href="mensagens.html">Mensagens</a></p></div></div></footer>'}
function initTheme(){theme(localStorage.getItem(THEME)||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));$$('[data-theme]').forEach(b=>b.onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark'))}
function doctorCard(d){return '<article class="doctor"><div class="doctor-photo"><img src="'+d.image+'" alt="'+d.name+'" loading="lazy"></div><div class="doctor-body"><span class="eyebrow">'+d.specialty+'</span><h3>'+d.name+'</h3><p>'+d.bio+'</p><div class="doctor-meta">'+d.tags.map(t=>'<span class="tag">'+t+'</span>').join('')+'</div><div class="doctor-footer"><span class="rating">★ '+d.rating+' · '+d.reviews+'</span><a class="primary" href="agendamento.html?doctor='+d.id+'">Ver agenda</a></div></div></article>'}
function renderDoctors(){const g=$('[data-doctors]');if(g)g.innerHTML=(D.doctors||[]).map(doctorCard).join('')}
function specialtyCard(s){return '<a class="specialty" href="especialidades.html#'+s.id+'"><div class="specialty-icon" style="background:'+s.color+'">'+s.icon+'</div><h3>'+s.name+'</h3><p>'+s.desc+'</p></a>'}
function renderSpecialties(){const g=$('[data-specialties]');if(g)g.innerHTML=(D.specialties||[]).map(specialtyCard).join('')}
function initBooking(){const root=$('[data-schedule]');if(!root)return;const doctorId=new URLSearchParams(location.search).get('doctor')||'ana';const doctor=D.doctors.find(x=>x.id===doctorId)||D.doctors[0];$('[data-selected-doctor]').textContent=doctor.name+' · '+doctor.specialty;root.innerHTML=['05/10','06/10','07/10','08/10'].map((day,i)=>'<article class="schedule-day"><strong>'+day+'</strong><div class="slots">'+['08:30','10:00','14:30','16:00'].map(t=>'<button class="slot" data-slot="'+day+' '+t+'">'+t+'</button>').join('')+'</div></article>').join('');$$('[data-slot]').forEach(b=>b.onclick=()=>{$$('[data-slot]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');localStorage.setItem('helia-selected-slot',b.dataset.slot)});const form=$('[data-booking-form]');if(form)form.onsubmit=e=>{e.preventDefault();const slot=localStorage.getItem('helia-selected-slot');if(!slot){alert('Selecione um horário.');return}const arr=JSON.parse(localStorage.getItem(APPT)||'[]');arr.unshift({id:'HLA-'+Date.now().toString().slice(-4),doctor:doctor.name,specialty:doctor.specialty,date:slot.split(' ')[0],time:slot.split(' ')[1],type:'Presencial',status:'Confirmada'});localStorage.setItem(APPT,JSON.stringify(arr));location.href='portal.html'}}
function allAppointments(){return [...(JSON.parse(localStorage.getItem(APPT)||'[]')),...(D.appointments||[])]}
function renderAppointments(){const r=$('[data-appointments]');if(r)r.innerHTML='<div class="table"><div class="table-row header"><span>Consulta</span><span>Data</span><span>Tipo</span><span>Status</span></div>'+allAppointments().map(a=>'<div class="table-row"><strong>'+a.specialty+'<br><small>'+a.doctor+'</small></strong><span>'+a.date+' · '+a.time+'</span><span>'+a.type+'</span><span>'+a.status+'</span></div>').join('')+'</div>'}
function renderExams(){const g=$('[data-exams]');if(g)g.innerHTML=(D.exams||[]).map(e=>'<article class="exam-card"><span class="eyebrow">'+e.lab+'</span><h3>'+e.name+'</h3><p>'+e.date+' · '+e.status+'</p><strong>'+e.highlight+'</strong><div style="margin-top:12px"><button class="secondary">Ver resultado</button></div></article>').join('')}
function renderMessages(){const list=$('[data-message-list]'),view=$('[data-message-view]');if(!list||!view)return;list.innerHTML=(D.messages||[]).map((m,i)=>'<article class="message-item '+(i===0?'active':'')+'" data-message="'+m.id+'"><strong>'+m.from+'</strong><div>'+m.subject+'</div><small>'+m.time+'</small></article>').join('');const show=id=>{const m=D.messages.find(x=>x.id===id)||D.messages[0];view.innerHTML='<span class="eyebrow">'+m.from+'</span><h2>'+m.subject+'</h2><p>'+m.body+'</p><button class="primary">Responder</button>'};show(D.messages[0].id);$$('[data-message]').forEach(el=>el.onclick=()=>{$$('[data-message]').forEach(x=>x.classList.remove('active'));el.classList.add('active');show(el.dataset.message)})}
function initSearch(){const f=$('[data-quick-search]');if(f)f.onsubmit=e=>{e.preventDefault();const d=new FormData(f);location.href='agendamento.html?specialty='+encodeURIComponent(d.get('specialty')||'')}}
function init(){shell();initTheme();renderDoctors();renderSpecialties();initBooking();renderAppointments();renderExams();renderMessages();initSearch()}
document.addEventListener('DOMContentLoaded',init);