const D=window.HELIA_DATA||{};const $=(s,r=document)=>r.querySelector(s);const qa=(s,r=document)=>[...r.querySelectorAll(s)];const THEME='helia-theme';const APPT='helia-demo-appointments';const SLOT='helia-selected-slot';const storageGet=k=>{try{return localStorage.getItem(k)}catch{return null}};const storageSet=(k,v)=>{try{localStorage.setItem(k,v);return true}catch{return false}};const storageJsonArray=k=>{const raw=storageGet(k);if(!raw)return[];try{const value=JSON.parse(raw);return Array.isArray(value)?value:[]}catch{return[]}};
function theme(v){const next=v==='dark'?'dark':'light';document.documentElement.dataset.theme=next;storageSet(THEME,next);qa('[data-theme-toggle]').forEach(b=>{b.textContent=next==='dark'?'☀':'☾';b.setAttribute('aria-label',next==='dark'?'Ativar modo claro':'Ativar modo escuro')})}
function shell(){const h=$('[data-shell-header]');if(h)h.innerHTML='<header class="app-header"><div class="wrap app-header-row"><a class="brand" href="index.html"><span class="brand-mark"></span><span>HELIA</span></a><nav class="main-nav"><a href="especialidades.html">Especialidades</a><a href="equipe.html">Equipe</a><a href="agendamento.html">Agendamento</a><a href="portal.html">Portal</a></nav><div class="header-actions"><button class="icon-btn" data-theme-toggle aria-label="Ativar modo escuro">☾</button><a class="secondary" href="portal.html">Área do paciente</a><a class="primary" href="agendamento.html">Agendar</a></div></div></header>';const f=$('[data-shell-footer]');if(f)f.innerHTML='<nav class="mobile-nav"><a href="index.html">⌂<span>Início</span></a><a href="agendamento.html">＋<span>Agendar</span></a><a href="portal.html">▣<span>Portal</span></a><a href="mensagens.html">✉<span>Mensagens</span></a></nav><footer class="app-footer"><div class="wrap footer-grid"><div><div class="brand"><span class="brand-mark"></span><span>HELIA</span></div><p>Plataforma conceitual de cuidado integrado desenvolvida pela Alureal.</p></div><div><strong>Atendimento</strong><p><a href="agendamento.html">Agendar</a><br><a href="teleconsulta.html">Teleconsulta</a><br><a href="planos.html">Convênios</a></p></div><div><strong>Paciente</strong><p><a href="portal.html">Portal</a><br><a href="exames.html">Exames</a><br><a href="mensagens.html">Mensagens</a></p></div></div></footer>'}
function initTheme(){const raw=storageGet(THEME);const stored=raw==='dark'||raw==='light'?raw:null;let system='light';try{system=window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light'}catch{}theme(stored||system);qa('[data-theme-toggle]').forEach(b=>b.onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark'))}
function doctorCard(d){return '<article class="doctor"><div class="doctor-photo"><img src="'+d.image+'" alt="'+d.name+'" loading="lazy"></div><div class="doctor-body"><span class="eyebrow">'+d.specialty+'</span><h3>'+d.name+'</h3><p>'+d.bio+'</p><div class="doctor-meta">'+d.tags.map(t=>'<span class="tag">'+t+'</span>').join('')+'</div><div class="doctor-footer"><span class="rating">★ '+d.rating+' · '+d.reviews+'</span><a class="primary" href="agendamento.html?doctor='+d.id+'">Ver agenda</a></div></div></article>'}
function renderDoctors(){const g=$('[data-doctors]');if(g)g.innerHTML=(D.doctors||[]).map(doctorCard).join('')}
function specialtyCard(s){return '<a class="specialty" href="especialidades.html#'+s.id+'"><div class="specialty-icon" style="background:'+s.color+'">'+s.icon+'</div><h3>'+s.name+'</h3><p>'+s.desc+'</p></a>'}
function renderSpecialties(){const g=$('[data-specialties]');if(g)g.innerHTML=(D.specialties||[]).map(specialtyCard).join('')}
function initBooking(){const root=$('[data-schedule]');if(!root)return;const doctors=D.doctors||[];const params=new URLSearchParams(location.search);const doctorId=params.get('doctor');const specialtyParam=params.get('specialty');const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('pt-BR');const requestedSpecialty=specialtyParam?normalize(specialtyParam):'';const specialty=(D.specialties||[]).find(item=>normalize(item.id)===requestedSpecialty||normalize(item.name)===requestedSpecialty);const explicitDoctor=doctorId?doctors.find(item=>item.id===doctorId):null;let doctor=explicitDoctor;let notice='';if(!doctor&&specialtyParam){if(!specialty){notice='A especialidade informada não foi encontrada. Escolha uma especialidade válida para ver horários.'}else{doctor=doctors.find(item=>normalize(item.specialty)===normalize(specialty.name));if(!doctor)notice='Ainda não há profissionais disponíveis para esta opção.'}}else if(!doctor){doctor=doctors[0];if(doctorId)notice='O profissional informado não foi encontrado. Exibindo a agenda padrão.'}if(explicitDoctor&&specialtyParam&&(!specialty||normalize(explicitDoctor.specialty)!==normalize(specialty.name)))notice='Profissional selecionado; a escolha de profissional tem prioridade sobre a especialidade.';const selected=$('[data-selected-doctor]');if(selected)selected.textContent=doctor?doctor.name+' · '+doctor.specialty:'Nenhum profissional disponível';const status=$('[data-booking-status]');if(status)status.textContent=notice;if(!doctor){root.textContent='Nenhum horário disponível.';const form=$('[data-booking-form]');if(form)form.hidden=true;return}root.innerHTML=['05/10','06/10','07/10','08/10'].map(day=>'<article class="schedule-day"><strong>'+day+'</strong><div class="slots">'+['08:30','10:00','14:30','16:00'].map(t=>'<button class="slot" data-slot="'+day+' '+t+'">'+t+'</button>').join('')+'</div></article>').join('');qa('[data-slot]').forEach(b=>b.onclick=()=>{qa('[data-slot]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');storageSet(SLOT,b.dataset.slot)});const form=$('[data-booking-form]');if(form)form.onsubmit=e=>{e.preventDefault();const slot=storageGet(SLOT);if(!slot){alert('Selecione um horário.');return}const arr=storageJsonArray(APPT);arr.unshift({id:'HLA-'+Date.now().toString().slice(-4),doctor:doctor.name,specialty:doctor.specialty,date:slot.split(' ')[0],time:slot.split(' ')[1],type:'Presencial',status:'Confirmada'});storageSet(APPT,JSON.stringify(arr));location.href='portal.html'}}
function allAppointments(){return [...(storageJsonArray(APPT)),...(D.appointments||[])]}
function renderAppointments(){const r=$('[data-appointments]');if(r)r.innerHTML='<div class="table"><div class="table-row header"><span>Consulta</span><span>Data</span><span>Tipo</span><span>Status</span></div>'+allAppointments().map(a=>'<div class="table-row"><strong>'+a.specialty+'<br><small>'+a.doctor+'</small></strong><span>'+a.date+' · '+a.time+'</span><span>'+a.type+'</span><span>'+a.status+'</span></div>').join('')+'</div>'}
function renderExams(){const g=$('[data-exams]');if(g)g.innerHTML=(D.exams||[]).map(e=>'<article class="exam-card"><span class="eyebrow">'+e.lab+'</span><h3>'+e.name+'</h3><p>'+e.date+' · '+e.status+'</p><strong>'+e.highlight+'</strong><div style="margin-top:12px"><button class="secondary">Ver resultado</button></div></article>').join('')}
function renderMessages(){const list=$('[data-message-list]'),view=$('[data-message-view]');if(!list||!view)return;list.innerHTML=(D.messages||[]).map((m,i)=>'<article class="message-item '+(i===0?'active':'')+'" data-message="'+m.id+'"><strong>'+m.from+'</strong><div>'+m.subject+'</div><small>'+m.time+'</small></article>').join('');const show=id=>{const m=D.messages.find(x=>x.id===id)||D.messages[0];view.innerHTML='<span class="eyebrow">'+m.from+'</span><h2>'+m.subject+'</h2><p>'+m.body+'</p><button class="primary">Responder</button>'};show(D.messages[0].id);qa('[data-message]').forEach(el=>el.onclick=()=>{qa('[data-message]').forEach(x=>x.classList.remove('active'));el.classList.add('active');show(el.dataset.message)})}
function initSearch(){const f=$('[data-quick-search]');if(f)f.onsubmit=e=>{e.preventDefault();const d=new FormData(f);location.href='agendamento.html?specialty='+encodeURIComponent(d.get('specialty')||'')}}
const safeRun=(name,fn)=>{try{fn()}catch(error){console.error('[HELIA] '+name+' failed',error)}};
function init(){safeRun('shell',shell);safeRun('theme',initTheme);safeRun('doctors',renderDoctors);safeRun('specialties',renderSpecialties);safeRun('booking',initBooking);safeRun('appointments',renderAppointments);safeRun('exams',renderExams);safeRun('messages',renderMessages);safeRun('search',initSearch)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
